### PR TITLE
Km2- Ticket 18

### PR DESCRIPTION
**Pull request by Kmille15**
Fixes for #/ Ticket 18

Changes proposed in this pull request:
- Can view first 20 products on home page
-
-

How to test:
- git fetch
- git checkout km2
- Run 

@PushyDonkey/

### CODE REVIEW

**Comment by jeffdylansmith** [comment]
I think you need to add asp-controller="Products" to line 55 on the home index view to get the details link to work. - That fixed it on my machine.  I merged master locally or I would commit my changes here. - let me know if you want me to push anyway.

**Comment by Kmille15** [comment]
@jeffdylansmith  Nice catch. Changed it and is working now.

**Comment by therealrmac** [comment]
besides the editing you want to do to the partial and then the later linq statement to group by the 20 products by datecreated, I'd say 👍

**Comment by therealrmac** [comment]
merging, but not moving ticket into done yet

**Pull request merged**
