### PR TITLE
image upload works

### PR DESCRIPTION
**Pull request by therealrmac**
Fixes for #14

Changes proposed in this pull request:
- Can upload an image (if you want to) when creating a product to sell
- Modified the ProductController to accept the image on creation 
- images are uploaded to the database and then to the wwwroot/products folder

How to test:
- Pull my branch / run program
- Go to create a product and upload an image
- See image with its information on the product index

@PushyDonkey/

### CODE REVIEW

**Comment by RillistikPete** [comment]
looks good, resized in window.  👍

**Comment by jeffdylansmith** [comment]
Looks Awesome!!  Working perfectly on my end.

**Comment by Kmille15** [comment]
Looks good

**Comment by KyleKellums** [comment]
Images uploaded and displayed. Some features did not work on my machine (such as the dropdown for the date a product was created, and an image not formatting correctly). I'm going to recheck it with Chrome.

**Pull request merged**
